@startuml

Client -> Server: Authentication Request
Server --> Client: Authentication Response
Client -> Server: Another authentication Request
Server <-- Client: another authentication Response
@enduml



@startuml

Foo -> Foo1: To actor
Foo -> Foo2: To boundary
Foo -> Foo3: To control
Foo -> Foo4: To entity
Foo -> Foo5: To database
Foo -> Foo6: To collections
Foo -> Foo7: To queue

@enduml



@startuml

actor Bob #red

participant Alice
participant "У меня очень\nдлинное имя" as L #99FF99
Alice->Bob: Authentication Request
Bob->Alice: Authentication Response
Bob->L: Log transaction
@enduml

@startuml

participant Last order 30
participant Middle order 20
participant First order 10

@enduml

@startuml
Alice -> Alice: Это сигнал к самому себе.\nТакже это является демострацией\nмногострочного \nтекста.
@enduml



@startuml
skinparam sequenceMessageAlign right

Bob  -> Alice : Request
Alice -> Bob : Response
@enduml


@startuml
skinparam sequenceMessageBelowArrow true

Bob  -> Alice : дай 5 евро
Alice -> Bob : нет
@enduml


@startuml
Bob ->x Alice
Bob -> Alice
Bob ->> Alice
Bob -\ Alice
Bob //- Alice

Bob ->o Alice
Bob o\\-- Alice

Bob <-> Alice

Bob <->o Alice
@enduml



@startuml
skinparam sequenceMessageBelowArrow true

Bob  -[#red]> Alice :hello
Alice -[#0000FF]-> Bob : ok
@enduml


@startuml
autonumber 1.1.1
Alice -> Bob: Authentication request
Bob --> Alice: Response

autonumber inc A

Alice -> Bob: Another authentication request
Bob --> Alice: Response

autonumber inc B

Alice -> Bob: Another authentication request
Bob --> Alice: Response

autonumber inc A

Alice -> Bob: Another authentication request
autonumber inc B
Bob --> Alice: Response

@enduml



@startuml
Alice -> Bob : message 1
Alice -> Bob : message 2

newpage

Alice -> Bob : message 3
Alice -> Bob : message 4

newpage A title for the \nlast page

Alice -> Bob : message 5
Alice -> Bob : message 6

@enduml




@startuml
Alice -> Bob: Authentication Request

alt successful case

    Bob -> Alice: Authentication Accepted

else some kind of failure

    Bob -> Alice: Authentication Failure
    group My own label
    Alice -> Log: Log attack start
        loop 1000 times
        Alice -> Bob: DNS Attack
        end

else Another type of failure
Bob -> Alice: Please repeat

end
@enduml


@startuml
Alice->Bob: Hi
note left: this first note

Bob->Alice : yes
note right: this another note

Bob->Bob : i think about it
note left
notes
can fill
more string
end note
@enduml


@startuml
participant Alice
participant Bob
note left of Alice #Aqua
Будет отображено
слева от Алисы
end note



note right of Alice: Будет отображено справа от Алисы

note over Alice: Будет отображено над Алисой.

note over Alice, Bob #FFAAAA: Будет отображено\n над Алисой и Бобом.
note over Bob, Alice
А это еще
один пример
длинной заметки.
end note 
@enduml


@startuml
==Initialization==

Alice -> Bob: Authentication Request
Bob --> Alice: Authentication Response


== Repetition ==


Alice -> Bob: Another authentication Request
Alice <-- Bob: another authentication Response

@enduml



@startuml
Bob -> Alice : Hi
activate Alice
Alice -> Alice: какое-то действие
return пока
@enduml



@startuml 
title __Simple__ communication example\non several LifelineStrategy

Alice -> Bob: Authentication Request
Bob -> Alice: Authentication Response
@enduml

@startuml
box "Internal Service" #LightBlue
participant Bob
participant Alice
end box
participant Other
Bob -> Alice : hello
Alice -> Other: hello
@enduml

@startuml
Alice -> Bob: Запрос авторизации
alt#Gold #LightBlue Успешный кейс
Bob -> Alice: Запрос удовлетворен
else #Pink Ошибка
Bob -> Alice: Запрос отклонен
end
@enduml